version: 2

before:
  hooks:
    - go mod tidy
    - task completions:gen

builds:
  - main: ./cmd/cmt
    binary: cmt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - completions/*

# Package formats for Linux distributions.
# Note: GPG signing can be enabled by setting environment variables:
#   - NFPM_PASSPHRASE (for all packages)
#   - Or format-specific: NFPM_CMT_DEB_PASSPHRASE, NFPM_CMT_RPM_PASSPHRASE, etc.
nfpms:
  - id: packages
    package_name: cmt
    vendor: Angus Peart
    homepage: "https://github.com/gussy/cmt"
    maintainer: "Angus Peart <angusp@gmail.com>"
    description: "Generate contextual git commit messages using Claude AI"
    license: MIT

    formats:
      - deb
      - rpm
      - apk
      - archlinux

    bindir: /usr/bin

    # Include shell completions and documentation.
    contents:
      - src: ./completions/cmt.bash
        dst: /usr/share/bash-completion/completions/cmt
        file_info:
          mode: 0644
      - src: ./completions/_cmt
        dst: /usr/share/zsh/site-functions/_cmt
        file_info:
          mode: 0644
      - src: ./completions/cmt.fish
        dst: /usr/share/fish/vendor_completions.d/cmt.fish
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/cmt/copyright
        file_info:
          mode: 0644
      - src: ./README.md
        dst: /usr/share/doc/cmt/README.md
        file_info:
          mode: 0644

    # Dependencies (none required - static binary).
    dependencies: []

    # Recommended packages for shell completion support.
    recommends:
      - bash-completion

    # Package metadata.
    section: utils
    priority: optional

homebrew_casks:
  - repository:
      owner: gussy
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/gussy/cmt"
    description: "Generate contextual git commit messages using Claude AI"
    license: "MIT"
    binaries:
      - cmt
    completions:
      bash: completions/cmt.bash
      zsh: completions/_cmt
      fish: completions/cmt.fish
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmt"]
          end
    caveats: |
      Note: This tool removes macOS quarantine attributes to allow execution.
      The binary is not code-signed or notarized by Apple.

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: false
  prerelease: auto